#!/bin/sh
DOMAIN_FILE=$1
PROBLEM_FILE=$2
PLANNER_PATH="/root/projects/lapkt/compiled_planners/siw"

echo "[INFO] Running LAPKT (siw):"
echo "[METRIC] Domain: $DOMAIN_FILE"
echo "[METRIC] Problem: $PROBLEM_FILE"

# Wallclock Start
START_TIME=$(date +%s.%N)

# Execute and save Output 
OUTPUT=$("$PLANNER_PATH" --domain "$DOMAIN_FILE" --problem "$PROBLEM_FILE")

# Wallclock End
END_TIME=$(date +%s.%N)
RUNTIME_WALL_S=$(python3 -c "print(round($END_TIME - $START_TIME, 6))")


echo "$OUTPUT"

# Plan cost extract
PLAN_COST=$(echo "$OUTPUT" | grep "Plan found with cost:" | awk '{print $5}')

# Intern Runtime 
RUNTIME_INTERNAL_S=$(echo "$OUTPUT" | grep "Total time:" | awk '{print $3}')

# Results
if [ -n "$PLAN_COST" ]; then
    echo "[RESULT] STATUS: SUCCESS"
    echo "[METRIC] PlanCost: $PLAN_COST"
else
    echo "[RESULT] STATUS: FAILURE"
    echo "[METRIC] PlanCost: N/A"
fi


echo "[METRIC] Runtime_internal_s: $RUNTIME_INTERNAL_S"
echo "[METRIC] Runtime_wall_s: $RUNTIME_WALL_S"