#!/bin/sh
DOMAIN_FILE=$1
PROBLEM_FILE=$2

echo "[INFO] Running Mercury:"
echo "  Domain: $DOMAIN_FILE"
echo "  Problem: $PROBLEM_FILE"

/opt/mercury/seq-agl-mercury/plan "$DOMAIN_FILE" "$PROBLEM_FILE" mercury_plan.sol

