#!/bin/sh
DOMAIN_FILE=$1
PROBLEM_FILE=$2

echo "[INFO] Running LPG:"
echo "  Domain: $DOMAIN_FILE"
echo "  Problem: $PROBLEM_FILE"

# Start Wallclock
START_TIME=$(date +%s.%N)

/opt/lpg/lpg-td/lpg-td \
    -o "$DOMAIN_FILE" \
    -f "$PROBLEM_FILE" \
    -n 1 \
    -cputime 300 \
    -v off > /workspace/lpg_output.txt

# Wallclock-End
END_TIME=$(date +%s.%N)
RUNTIME_WALL_S=$(python3 -c "print(round($END_TIME - $START_TIME, 6))")

# Extrahct plancost and total time
PLAN_COST=$(grep "Actions:" /workspace/lpg_output.txt | awk '{print $2}')
RUNTIME_INTERNAL_S=$(grep "Total time:" /workspace/lpg_output.txt | awk '{print $3}')

if [ -n "$PLAN_COST" ]; then
    echo "[RESULT] STATUS: SUCCESS"
    echo "[METRIC] PlanCost: $PLAN_COST"
else
    echo "[RESULT] STATUS: FAILURE"
    echo "[METRIC] PlanCost: N/A"
fi

echo "[METRIC] Runtime_internal_s: $RUNTIME_INTERNAL_S"
echo "[METRIC] Runtime_wall_s: $RUNTIME_WALL_S"

